/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['ang-daterange-picker[_ngcontent-%COMP%] {\n  position: absolute;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0R1c3Rpbi9EZXZlbG9wbWVudC9jb250cmliL25nMi1kYXRlcmFuZ2UtcGlja2VyL3NyYy9hbmcuZGF0ZXJhbmdlLnBpY2tlci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL0R1c3Rpbi9EZXZlbG9wbWVudC9jb250cmliL25nMi1kYXRlcmFuZ2UtcGlja2VyL3NyYy9hbmcuZGF0ZXJhbmdlLnBpY2tlci5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
