/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/daterange.picker.module';
import * as i2 from '@angular/common';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/http';
import * as i5 from '@angular/cdk/bidi';
import * as i6 from '@angular/platform-browser';
import * as i7 from '@angular/cdk/platform';
import * as i8 from '@angular/material/core';
import * as i9 from '@angular/material/card';
import * as i10 from '@angular/material/form-field';
import * as i11 from '@angular/material/input';
export const DaterangePickerModuleNgFactory:i0.NgModuleFactory<i1.DaterangePickerModule> = i0.ɵcmf(i1.DaterangePickerModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.ɵi,
          i3.ɵi,([] as any[])),i0.ɵmpd(4608,i4.BrowserXhr,i4.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i4.ResponseOptions,i4.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,
              i4.XSRFStrategy,i4.ɵb,([] as any[])),i0.ɵmpd(4608,i4.XHRBackend,i4.XHRBackend,
              [i4.BrowserXhr,i4.ResponseOptions,i4.XSRFStrategy]),i0.ɵmpd(4608,i4.RequestOptions,
              i4.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i4.Http,i4.ɵc,[i4.XHRBackend,
              i4.RequestOptions]),i0.ɵmpd(4608,i3.FormBuilder,i3.FormBuilder,([] as any[])),
          i0.ɵmpd(6144,i5.DIR_DOCUMENT,(null as any),[i6.DOCUMENT]),i0.ɵmpd(4608,i5.Directionality,
              i5.Directionality,[[2,i5.DIR_DOCUMENT]]),i0.ɵmpd(4608,i7.Platform,i7.Platform,
              ([] as any[])),i0.ɵmpd(512,i2.CommonModule,i2.CommonModule,([] as any[])),
          i0.ɵmpd(512,i3.ɵba,i3.ɵba,([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i4.HttpModule,i4.HttpModule,([] as any[])),
          i0.ɵmpd(512,i3.ReactiveFormsModule,i3.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i8.CompatibilityModule,i8.CompatibilityModule,([] as any[])),
          i0.ɵmpd(512,i5.BidiModule,i5.BidiModule,([] as any[])),i0.ɵmpd(256,i8.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i8.MdCommonModule,i8.MdCommonModule,
              [[2,i6.DOCUMENT],[2,i8.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i9.MdCardModule,
              i9.MdCardModule,([] as any[])),i0.ɵmpd(512,i7.PlatformModule,i7.PlatformModule,
              ([] as any[])),i0.ɵmpd(512,i10.MdFormFieldModule,i10.MdFormFieldModule,
              ([] as any[])),i0.ɵmpd(512,i11.MdInputModule,i11.MdInputModule,([] as any[])),
          i0.ɵmpd(512,i1.DaterangePickerModule,i1.DaterangePickerModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL0R1c3Rpbi9EZXZlbG9wbWVudC9jb250cmliL25nMi1kYXRlcmFuZ2UtcGlja2VyL3NyYy9kYXRlcmFuZ2UucGlja2VyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9EdXN0aW4vRGV2ZWxvcG1lbnQvY29udHJpYi9uZzItZGF0ZXJhbmdlLXBpY2tlci9zcmMvZGF0ZXJhbmdlLnBpY2tlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
