/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
var styles = ["ang-daterange-picker[_ngcontent-%COMP%] {\n  position: absolute;\n}"];
export { styles as styles };
//# sourceMappingURL=ang.daterange.picker.component.css.shim.ngstyle.js.map